// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZAI.Server.Database;

#nullable disable

namespace ZAI.Server.Migrations
{
    [DbContext(typeof(ZAIDbContext))]
    partial class ZAIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("ZAI.Shared.Database.AddressessEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adressess");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Słoneczna 1",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Makowa 5C",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Piaskowa 1b",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Pythonowa 16",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Javascriptowa 1",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Hakerska 21/37",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Drewniana 9/2",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Gruszkowa 4",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Humusowa 18",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Jana Wazy 13",
                            City = "Poznań",
                            District = "Poznańskie",
                            Province = "Wielkopolskie",
                            ZipCode = "60-001"
                        });
                });

            modelBuilder.Entity("ZAI.Shared.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("ZAI.Shared.Database.RoleLinks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("RolesLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleID = 1,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleID = 2,
                            UserID = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleID = 1,
                            UserID = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleID = 2,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("ZAI.Shared.Database.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrowserAgent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expired")
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("ZAI.Shared.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddTime = new DateTime(2022, 5, 19, 8, 14, 58, 232, DateTimeKind.Local).AddTicks(148),
                            Login = "user",
                            PasswordHash = "$2a$11$0UV5Ilxu5dswKKyLdmZobODOMShF4HQA74ejhiy4rJvZ8VBkJuSpy"
                        },
                        new
                        {
                            Id = 2,
                            AddTime = new DateTime(2022, 5, 19, 8, 14, 58, 384, DateTimeKind.Local).AddTicks(9261),
                            Login = "user2",
                            PasswordHash = "$2a$11$vKJvQHCPrwRKMWC7yrW6hecQTl.x5sO.adMMoGR51qqT7GlIenr4."
                        },
                        new
                        {
                            Id = 3,
                            AddTime = new DateTime(2022, 5, 19, 8, 14, 58, 532, DateTimeKind.Local).AddTicks(7866),
                            Login = "user3",
                            PasswordHash = "$2a$11$2hQCO0eMGHPaVounsUT8TepeiJPlwkdVJSFnJYJXjkvR1npqCLBVq"
                        });
                });

            modelBuilder.Entity("ZAI.Shared.Database.RoleLinks", b =>
                {
                    b.HasOne("ZAI.Shared.Database.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZAI.Shared.Database.User", "User")
                        .WithMany("RoleUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZAI.Shared.Database.Token", b =>
                {
                    b.HasOne("ZAI.Shared.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZAI.Shared.Database.User", b =>
                {
                    b.Navigation("RoleUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
